version: '3'

services:
        dbos:
                image: mysql:5.7
                volumes:
                        - mysql_storage_new:/var/lib/mysql
                restart: always       
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: Sandeep
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mydb


        joomlaos:
                image: joomla:latest
                restart: always
                depends_on:
                        - dbos
                ports:
                        - 8081:80
                environment:
                        JOOMLA_DB_HOST: dbos:3306
                        JOOMLA_DB_USER: Sandeep
                        JOOMLA_DB_PASSWORD: redhat
                        JOOMLA_DB_NAME: mydb
                volumes:
                        - jm_storage_new:/var/www/html

volumes:
        jm_storage_new:
        mysql_storage_new:


